package com.undeadscythes.hyperform;

/**
 * An {@link HyperScript} class can insert data into an output stream, this data
 * is generated by the {@link HyperScript#insert insert} method.
 * <p>
 * <b>NOTE: All implementing classes must provide a constructor that accepts no
 * arguments.</b>
 *
 * @author UndeadScythes
 */
public interface HyperScript {
    /**
     * Inject a {@link String} into an output stream. This method accepts an
     * argument {@link String}.
     */
    String insert(final String key);
}
